## 各csvの説明、kaggleの当コンペHPより

In [30]:
import pandas as pd 
df = pd.read_csv("HomeCredit_columns_description.csv")

### application_{train|test}.csv

This is the main table, broken into two files for Train (with TARGET) and Test (without TARGET).
Static data for all applications. One row represents one loan in our data sample.

メインの表。train.csvとtest.csvがある。全申請に関する統計情報が含まれている。各行は各々のローンに対応している

In [28]:
df[df["Table"]=="application_{train|test}.csv"].drop(["Table"],axis=1)

,Unnamed: 0,Unnamed: 0.1,Row,Description,Special
0,0,1,SK_ID_CURR,ID of loan in our sample,NaN
1,1,2,TARGET,Target variable (1 - client with payment diffi...,NaN
2,2,5,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,3,6,CODE_GENDER,Gender of the client,NaN
4,4,7,FLAG_OWN_CAR,Flag if the client owns a car,NaN
5,5,8,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN
6,6,9,CNT_CHILDREN,Number of children the client has,NaN
7,7,10,AMT_INCOME_TOTAL,Income of the client,NaN
8,8,11,AMT_CREDIT,Credit amount of the loan,NaN
9,9,12,AMT_ANNUITY,Loan annuity,NaN
10,10,13,AMT_GOODS_PRICE,For consumer loans it is the price of the good...,NaN
11,11,14,NAME_TYPE_SUITE,Who was accompanying client when he was applyi...,NaN
12,12,15,NAME_INCOME_TYPE,"Clients income type (businessman, working, mat...",NaN
13,13,16,NAME_EDUCATION_TYPE,Level of highest education the client achieved,NaN
14,14,17,NAME_FAMILY_STATUS,Family status of the client,NaN
15,15,18,NAME_HOUSING_TYPE,What is the housing situation of the client (r...,NaN
16,16,19,REGION_POPULATION_RELATIVE,Normalized population of region where client l...,normalized
17,17,20,DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application
18,18,21,DAYS_EMPLOYED,How many days before the application the perso...,time only relative to the application
19,19,22,DAYS_REGISTRATION,How many days before the application did clien...,time only relative to the application
20,20,23,DAYS_ID_PUBLISH,How many days before the application did clien...,time only relative to the application
21,21,24,OWN_CAR_AGE,Age of client's car,NaN
22,22,25,FLAG_MOBIL,"Did client provide mobile phone (1=YES, 0=NO)",NaN
23,23,26,FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)",NaN
24,24,27,FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN
25,25,28,FLAG_CONT_MOBILE,"Was mobile phone reachable (1=YES, 0=NO)",NaN
26,26,29,FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN
27,27,30,FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)",NaN
28,28,31,OCCUPATION_TYPE,What kind of occupation does the client have,NaN
29,29,32,CNT_FAM_MEMBERS,How many family members does client have,NaN
...,...,...,...,...,...
92,92,95,DEF_30_CNT_SOCIAL_CIRCLE,How many observation of client's social surrou...,NaN
93,93,96,OBS_60_CNT_SOCIAL_CIRCLE,How many observation of client's social surrou...,NaN
94,94,97,DEF_60_CNT_SOCIAL_CIRCLE,How many observation of client's social surrou...,NaN
95,95,98,DAYS_LAST_PHONE_CHANGE,How many days before application did client ch...,NaN
96,96,99,FLAG_DOCUMENT_2,Did client provide document 2,NaN
97,97,100,FLAG_DOCUMENT_3,Did client provide document 3,NaN
98,98,101,FLAG_DOCUMENT_4,Did client provide document 4,NaN
99,99,102,FLAG_DOCUMENT_5,Did client provide document 5,NaN
100,100,103,FLAG_DOCUMENT_6,Did client provide document 6,NaN
101,101,104,FLAG_DOCUMENT_7,Did client provide document 7,NaN
102,102,105,FLAG_DOCUMENT_8,Did client provide document 8,NaN
103,103,106,FLAG_DOCUMENT_9,Did client provide document 9,NaN
104,104,107,FLAG_DOCUMENT_10,Did client provide document 10,NaN
105,105,108,FLAG_DOCUMENT_11,Did client provide document 11,NaN
106,106,109,FLAG_DOCUMENT_12,Did client provide document 12,NaN
107,107,110,FLAG_DOCUMENT_13,Did client provide document 13,NaN
108,108,111,FLAG_DOCUMENT_14,Did client provide document 14,NaN
109,109,112,FLAG_DOCUMENT_15,Did client provide document 15,NaN
110,110,113,FLAG_DOCUMENT_16,Did client provide document 16,NaN
111,111,114,FLAG_DOCUMENT_17,Did client provide document 17,NaN
112,112,115,FLAG_DOCUMENT_18,Did client provide document 18,NaN
113,113,116,FLAG_DOCUMENT_19,Did client provide document 19,NaN
114,114,117,FLAG_DOCUMENT_20,Did client provide document 20,NaN
115,115,118,FLAG_DOCUMENT_21,Did client provide document 21,NaN
116,116,119,AMT_REQ_CREDIT_BUREAU_HOUR,Number of enquiries to Credit Bureau about the...,NaN
117,117,120,AMT_REQ_CREDIT_BUREAU_DAY,Number of enquiries to Credit Bureau about the...,NaN
118,118,121,AMT_REQ_CREDIT_BUREAU_WEEK,Number of enquiries to Credit Bureau about the...,NaN
119,119,122,AMT_REQ_CREDIT_BUREAU_MON,Number of enquiries to Credit Bureau about the...,NaN
120,120,123,AMT_REQ_CREDIT_BUREAU_QRT,Number of enquiries to Credit Bureau about the...,NaN
121,121,124,AMT_REQ_CREDIT_BUREAU_YEAR,Number of enquiries to Credit Bureau about the...,NaN

### bureau.csv

All client's previous credits provided by other financial institutions that were reported to Credit Bureau (for clients who have a loan in our sample).
For every loan in our sample, there are as many rows as number of credits the client had in Credit Bureau before the application date.

全クライアントの過去のクレジット情報（信用調査機関より提供）。全ローンについて、信用調査機関が所有していた、申請日付以前のクライアントのクレジット情報分だけ行が追加されている。

In [18]:
df[df["Table"]=="bureau.csv"].drop(["Table"],axis=1)

,Unnamed: 0,Row,Description,Special
122,125,SK_ID_CURR,ID of loan in our sample - one loan in our sam...,hashed
123,126,SK_BUREAU_ID,Recoded ID of previous Credit Bureau credit re...,hashed
124,127,CREDIT_ACTIVE,Status of the Credit Bureau (CB) reported credits,NaN
125,128,CREDIT_CURRENCY,Recoded currency of the Credit Bureau credit,recoded
126,129,DAYS_CREDIT,How many days before current application did c...,time only relative to the application
127,130,CREDIT_DAY_OVERDUE,Number of days past due on CB credit at the ti...,NaN
128,131,DAYS_CREDIT_ENDDATE,Remaining duration of CB credit (in days) at t...,time only relative to the application
129,132,DAYS_ENDDATE_FACT,Days since CB credit ended at the time of appl...,time only relative to the application
130,133,AMT_CREDIT_MAX_OVERDUE,Maximal amount overdue on the Credit Bureau cr...,NaN
131,134,CNT_CREDIT_PROLONG,How many times was the Credit Bureau credit pr...,NaN
132,135,AMT_CREDIT_SUM,Current credit amount for the Credit Bureau cr...,NaN
133,136,AMT_CREDIT_SUM_DEBT,Current debt on Credit Bureau credit,NaN
134,137,AMT_CREDIT_SUM_LIMIT,Current credit limit of credit card reported i...,NaN
135,138,AMT_CREDIT_SUM_OVERDUE,Current amount overdue on Credit Bureau credit,NaN
136,139,CREDIT_TYPE,"Type of Credit Bureau credit (Car, cash,...)",NaN
137,140,DAYS_CREDIT_UPDATE,How many days before loan application did last...,time only relative to the application
138,141,AMT_ANNUITY,Annuity of the Credit Bureau credit,NaN

### bureau_balance.csv

Monthly balances of previous credits in Credit Bureau.
This table has one row for each month of history of every previous credit reported to Credit Bureau – i.e the table has (#loans in sample * # of relative previous credits * # of months where we have some history observable for the previous credits) rows.

bureau.csvを月別にバランスしたもの？

In [19]:
df[df["Table"]=="bureau_balance.csv"].drop(["Table"],axis=1)

,Unnamed: 0,Row,Description,Special
139,142,SK_BUREAU_ID,Recoded ID of Credit Bureau credit (unique cod...,hashed
140,143,MONTHS_BALANCE,Month of balance relative to application date ...,time only relative to the application
141,144,STATUS,Status of Credit Bureau loan during the month ...,NaN

### POS_CASH_balance.csv

Monthly balance snapshots of previous POS (point of sales) and cash loans that the applicant had with Home Credit.
This table has one row for each month of history of every previous credit in Home Credit (consumer credit and cash loans) related to loans in our sample – i.e. the table has (#loans in sample * # of relative previous credits * # of months in which we have some history observable for the previous credits) rows.

よくわからん。

In [20]:
df[df["Table"]=="POS_CASH_balance.csv"].drop(["Table"],axis=1)

,Unnamed: 0,Row,Description,Special
142,145,SK_ID_PREV,ID of previous credit in Home Credit related t...,NaN
143,146,SK_ID_CURR,ID of loan in our sample,NaN
144,147,MONTHS_BALANCE,Month of balance relative to application date ...,time only relative to the application
145,148,CNT_INSTALMENT,Term of previous credit (can change over time),NaN
146,149,CNT_INSTALMENT_FUTURE,Installments left to pay on the previous credit,NaN
147,150,NAME_CONTRACT_STATUS,Contract status during the month,NaN
148,151,SK_DPD,DPD (days past due) during the month of previo...,NaN
149,152,SK_DPD_DEF,DPD during the month with tolerance (debts wit...,NaN

### credit_card_balance.csv

Monthly balance snapshots of previous credit cards that the applicant has with Home Credit.
This table has one row for each month of history of every previous credit in Home Credit (consumer credit and cash loans) related to loans in our sample – i.e. the table has (#loans in sample * # of relative previous credit cards * # of months where we have some history observable for the previous credit card) rows.

よくわからん。

In [21]:
df[df["Table"]=="credit_card_balance.csv"].drop(["Table"],axis=1)

,Unnamed: 0,Row,Description,Special
150,153,SK_ID_PREV,ID of previous credit in Home credit related t...,hashed
151,154,SK_ID_CURR,ID of loan in our sample,hashed
152,155,MONTHS_BALANCE,Month of balance relative to application date ...,time only relative to the application
153,156,AMT_BALANCE,Balance during the month of previous credit,NaN
154,157,AMT_CREDIT_LIMIT_ACTUAL,Credit card limit during the month of the prev...,NaN
155,158,AMT_DRAWINGS_ATM_CURRENT,Amount drawing at ATM during the month of the ...,NaN
156,159,AMT_DRAWINGS_CURRENT,Amount drawing during the month of the previou...,NaN
157,160,AMT_DRAWINGS_OTHER_CURRENT,Amount of other drawings during the month of t...,NaN
158,161,AMT_DRAWINGS_POS_CURRENT,Amount drawing or buying goods during the mont...,NaN
159,162,AMT_INST_MIN_REGULARITY,Minimal installment for this month of the prev...,NaN
160,163,AMT_PAYMENT_CURRENT,How much did the client pay during the month o...,NaN
161,164,AMT_PAYMENT_TOTAL_CURRENT,How much did the client pay during the month i...,NaN
162,165,AMT_RECEIVABLE_PRINCIPAL,Amount receivable for principal on the previou...,NaN
163,166,AMT_RECIVABLE,Amount receivable on the previous credit,NaN
164,167,AMT_TOTAL_RECEIVABLE,Total amount receivable on the previous credit,NaN
165,168,CNT_DRAWINGS_ATM_CURRENT,Number of drawings at ATM during this month on...,NaN
166,169,CNT_DRAWINGS_CURRENT,Number of drawings during this month on the pr...,NaN
167,170,CNT_DRAWINGS_OTHER_CURRENT,Number of other drawings during this month on ...,NaN
168,171,CNT_DRAWINGS_POS_CURRENT,Number of drawings for goods during this month...,NaN
169,172,CNT_INSTALMENT_MATURE_CUM,Number of paid installments on the previous cr...,NaN
170,173,NAME_CONTRACT_STATUS,"Contract status (active signed,...) on the pre...",NaN
171,174,SK_DPD,DPD (Days past due) during the month on the pr...,NaN
172,175,SK_DPD_DEF,DPD (Days past due) during the month with tole...,NaN

### previous_application.csv

All previous applications for Home Credit loans of clients who have loans in our sample.
There is one row for each previous application related to loans in our data sample.

In [22]:
df[df["Table"]=="previous_application.csv"].drop(["Table"],axis=1)

,Unnamed: 0,Row,Description,Special
173,176,SK_ID_PREV,ID of previous credit in Home credit related t...,hashed
174,177,SK_ID_CURR,ID of loan in our sample,hashed
175,178,NAME_CONTRACT_TYPE,"Contract product type (Cash loan, consumer loa...",NaN
176,179,AMT_ANNUITY,Annuity of previous application,NaN
177,180,AMT_APPLICATION,For how much credit did client ask on the prev...,NaN
178,181,AMT_CREDIT,Final credit amount on the previous applicatio...,NaN
179,182,AMT_DOWN_PAYMENT,Down payment on the previous application,NaN
180,183,AMT_GOODS_PRICE,Goods price of good that client asked for (if ...,NaN
181,184,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...,NaN
182,185,HOUR_APPR_PROCESS_START,Approximately at what day hour did the client ...,rounded
183,186,FLAG_LAST_APPL_PER_CONTRACT,Flag if it was last application for the previo...,NaN
184,187,NFLAG_LAST_APPL_IN_DAY,Flag if the application was the last applicati...,NaN
185,188,NFLAG_MICRO_CASH,Flag Micro finance loan,NaN
186,189,RATE_DOWN_PAYMENT,Down payment rate normalized on previous credit,normalized
187,190,RATE_INTEREST_PRIMARY,Interest rate normalized on previous credit,normalized
188,191,RATE_INTEREST_PRIVILEGED,Interest rate normalized on previous credit,normalized
189,192,NAME_CASH_LOAN_PURPOSE,Purpose of the cash loan,NaN
190,193,NAME_CONTRACT_STATUS,"Contract status (approved, cancelled, ...) of ...",NaN
191,194,DAYS_DECISION,Relative to current application when was the d...,time only relative to the application
192,195,NAME_PAYMENT_TYPE,Payment method that client chose to pay for th...,NaN
193,196,CODE_REJECT_REASON,Why was the previous application rejected,NaN
194,197,NAME_TYPE_SUITE,Who accompanied client when applying for the p...,NaN
195,198,NAME_CLIENT_TYPE,Was the client old or new client when applying...,NaN
196,199,NAME_GOODS_CATEGORY,What kind of goods did the client apply for in...,NaN
197,200,NAME_PORTFOLIO,"Was the previous application for CASH, POS, CA...",NaN
198,201,NAME_PRODUCT_TYPE,Was the previous application x-sell o walk-in,NaN
199,202,CHANNEL_TYPE,Through which channel we acquired the client o...,NaN
200,203,SELLERPLACE_AREA,Selling area of seller place of the previous a...,NaN
201,204,NAME_SELLER_INDUSTRY,The industry of the seller,NaN
202,205,CNT_PAYMENT,Term of previous credit at application of the ...,NaN
203,206,NAME_YIELD_GROUP,Grouped interest rate into small medium and hi...,grouped
204,207,PRODUCT_COMBINATION,Detailed product combination of the previous a...,NaN
205,208,DAYS_FIRST_DRAWING,Relative to application date of current applic...,time only relative to the application
206,209,DAYS_FIRST_DUE,Relative to application date of current applic...,time only relative to the application
207,210,DAYS_LAST_DUE_1ST_VERSION,Relative to application date of current applic...,time only relative to the application
208,211,DAYS_LAST_DUE,Relative to application date of current applic...,time only relative to the application
209,212,DAYS_TERMINATION,Relative to application date of current applic...,time only relative to the application
210,213,NFLAG_INSURED_ON_APPROVAL,Did the client requested insurance during the ...,NaN

### installments_payments.csv

Repayment history for the previously disbursed credits in Home Credit related to the loans in our sample.
There is a) one row for every payment that was made plus b) one row each for missed payment.
One row is equivalent to one payment of one installment OR one installment corresponding to one payment of one previous Home Credit credit related to loans in our sample.

In [23]:
df[df["Table"]=="installments_payments.csv"].drop(["Table"],axis=1)

,Unnamed: 0,Row,Description,Special
211,214,SK_ID_PREV,ID of previous credit in Home credit related t...,hashed
212,215,SK_ID_CURR,ID of loan in our sample,hashed
213,216,NUM_INSTALMENT_VERSION,Version of installment calendar (0 is for cred...,NaN
214,217,NUM_INSTALMENT_NUMBER,On which installment we observe payment,NaN
215,218,DAYS_INSTALMENT,When the installment of previous credit was su...,time only relative to the application
216,219,DAYS_ENTRY_PAYMENT,When was the installments of previous credit p...,time only relative to the application
217,220,AMT_INSTALMENT,What was the prescribed installment amount of ...,NaN
218,221,AMT_PAYMENT,What the client actually paid on previous cred...,NaN

### HomeCredit_columns_description.csv

This file contains descriptions for the columns in the various data files.

<img src="home_credit.png">